name: unstructured-bargaining-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - polars=0.20.6
  - numpy=1.26.4
  - scipy=1.13.0
  - statsmodels=0.14.1
  - jupyterlab=4.1.7
  - nbconvert=7.16.3
